// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Company struct {
	ID          string `json:"id"`
	CompanyName string `json:"companyName"`
	Adress      string `json:"adress"`
	Domain      string `json:"domain"`
}

type Job struct {
	ID        string   `json:"id"`
	JobTitle  string   `json:"jobTitle"`
	JobSalary string   `json:"jobSalary"`
	Company   *Company `json:"company,omitempty"`
}

type NewCompany struct {
	CompanyName string `json:"companyName"`
	Adress      string `json:"adress"`
	Domain      string `json:"domain"`
}

type NewJob struct {
	JobTitle  string `json:"jobTitle"`
	JobSalary string `json:"jobSalary"`
	ID        string `json:"id"`
}

type NewUser struct {
	UserName string `json:"userName"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID           string `json:"id"`
	UserName     string `json:"userName"`
	Email        string `json:"email"`
	PasswordHash string `json:"passwordHash"`
}

type UserLogin struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
